# Generated by Django 3.1.6 on 2022-01-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_User',
            fields=[
                ('username', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=512, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, verbose_name='安全邮箱')),
                ('login_stop', models.BooleanField(default=True, verbose_name='账号是否正常')),
                ('capacity', models.DecimalField(decimal_places=3, default=10.0, max_digits=5, verbose_name='存储总容量(G)')),
                ('Usedspace', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='已用容量(G)')),
                ('Residual_capacity', models.DecimalField(decimal_places=3, default=10, max_digits=5, verbose_name='剩余容量(G)')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='最晚修改用户信息的日期时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='最早创建用户信息的日期时间')),
                ('name', models.CharField(blank=True, max_length=8, verbose_name='昵称')),
                ('login_errnum', models.IntegerField(default=0, verbose_name='用户密码输错次数')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='T_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.CharField(max_length=800, verbose_name='文件名')),
                ('myfile', models.FileField(upload_to='upload', verbose_name='文件类型')),
                ('Upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期日期')),
                ('createTime', models.DateTimeField(blank=True, null=True, verbose_name='删除日期')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('File_Available', models.BooleanField(default=True, verbose_name='文件是否可用')),
                ('File_size', models.CharField(max_length=800, verbose_name='文件大小')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.t_user', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '文件表',
                'db_table': '文件信息',
            },
        ),
    ]
