# Generated by Django 3.1.6 on 2022-02-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_file',
            name='file_is_folder',
            field=models.CharField(default='', max_length=8000, verbose_name='文件所在的目录'),
            preserve_default=False,
        ),
    ]
